In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#Data Collection and Preprocessing


In [ ]:
movies_data = pd.read_csv("movies.csv", encoding="utf-8", skiprows=[2158])

In [ ]:
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
movies_data.shape

(2157, 24)

In [ ]:
#selecting relevant features for recommendation:
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']


In [ ]:
# replacing the null valuess with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna(" ")

In [ ]:
# combining all the 5 selected features
combined_features = movies_data['genres'] +' '+ movies_data['keywords'] +' '+ movies_data['tagline']+' '+ movies_data['cast'] +' '+movies_data['director']
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
2152    Science Fiction Drama Romance deja vu regret j...
2153    Comedy Romance brother sister relationship mar...
2154    Action Crime Drama Thriller police los angeles...
2155    Comedy Action Science Fiction end of the world...
2156    Action Adventure Crime Family Mystery californ...
Length: 2157, dtype: object


In [ ]:
#convertring the text data to feature vectors
vectorizer = TfidfVectorizer()

In [ ]:

feature_vectors = vectorizer.fit_transform(combined_features)

In [ ]:
print(feature_vectors)

  (0, 1331)	0.1705881362328062
  (0, 4361)	0.1176625647213352
  (0, 7313)	0.19429329222236097
  (0, 5704)	0.16161545915971692
  (0, 4890)	0.23546833258056069
  (0, 8199)	0.15788091861395873
  (0, 9349)	0.2019246479290861
  (0, 7870)	0.20902577113882656
  (0, 7473)	0.21176317659100588
  (0, 9722)	0.20649132955233054
  (0, 9568)	0.2216017052529256
  (0, 7491)	0.14819011938689014
  (0, 6417)	0.25917348857011546
  (0, 6238)	0.09253223122780092
  (0, 9564)	0.12296474374513817
  (0, 8570)	0.0696214175255609
  (0, 2762)	0.2417036042014706
  (0, 7996)	0.21176317659100588
  (0, 1765)	0.2417036042014706
  (0, 9294)	0.1265444069176788
  (0, 8058)	0.32323091831943385
  (0, 3291)	0.16507287670044485
  (0, 1685)	0.24933495990819574
  (0, 2030)	0.24933495990819574
  (0, 3041)	0.09862819792701716
  :	:
  (2156, 4994)	0.212973263548291
  (2156, 7290)	0.16828476636139988
  (2156, 8738)	0.18772858643294138
  (2156, 7958)	0.185081531624774
  (2156, 2310)	0.18032988699617855
  (2156, 3460)	0.19902739758653

In [ ]:
#cosine similarity
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.06504991 0.03454261 ... 0.00508988 0.048929   0.01704207]
 [0.06504991 1.         0.0286152  ... 0.00448778 0.07362159 0.02582479]
 [0.03454261 0.0286152  1.         ... 0.03740738 0.00465622 0.06998495]
 ...
 [0.00508988 0.00448778 0.03740738 ... 1.         0.00472284 0.01492004]
 [0.048929   0.07362159 0.00465622 ... 0.00472284 1.         0.00444883]
 [0.01704207 0.02582479 0.06998495 ... 0.01492004 0.00444883 1.        ]]


In [ ]:
print(similarity.shape)

(2157, 2157)


In [ ]:
# creating a list with all the movie names given in the dataset
movie_name= input("Give the name of your favourite movie: ")

Give the name of your favourite movie: iron-man


In [ ]:
#list of all the movies
list_all_titles = movies_data["title"].tolist()

In [ ]:
# finding the close match for the movie name given by the user
find_close_matches = difflib.get_close_matches(movie_name, list_all_titles )

In [ ]:
print((find_close_matches))

['Iron Man']


In [ ]:
close_match = find_close_matches[0]

In [ ]:
print(close_match)

Iron Man


In [ ]:
# finding the index of the movie with title
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

In [ ]:
print(index_of_the_movie)

68


In [ ]:
print(similarity[index_of_the_movie])

[0.02853439 0.05132065 0.01076467 ... 0.00479474 0.02115448 0.01605388]


In [ ]:
# getting a list of similar movies from similarity matrix
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.028534391229125957), (1, 0.05132065057479884), (2, 0.010764669852304782), (3, 0.005072543287007002), (4, 0.027186506537932205), (5, 0.010607803360213332), (6, 0.0799329184255604), (7, 0.22319988215604714), (8, 0.005978797182596573), (9, 0.06624654259905201), (10, 0.0665019138996635), (11, 0.008994600619948952), (12, 0.010607562388158454), (13, 0.009235551239977064), (14, 0.0853903762308281), (15, 0.005516649099676998), (16, 0.2141357126916174), (17, 0.009990394650295768), (18, 0.03881400141452835), (19, 0.08026555578544557), (20, 0.0674137608857277), (21, 0.008671255597093974), (22, 0.005300230488261847), (23, 0.00499194877039573), (24, 0.00913035222303476), (25, 0.0), (26, 0.20129720491438394), (27, 0.026159894702632292), (28, 0.05669136498911423), (29, 0.010643620842691751), (30, 0.06749798453473788), (31, 0.29900581015660854), (32, 0.02980038338293992), (33, 0.11471450976786662), (34, 0.0), (35, 0.03041721836284323), (36, 0.027682914674470583), (37, 0.006044830327682718), (38

In [ ]:
 sorted_similarity_movies = sorted(similarity_score, key=lambda x:x[1], reverse=True)
 print(sorted_similarity_movies)

[(68, 1.0000000000000002), (79, 0.39004649109626666), (31, 0.29900581015660854), (7, 0.22319988215604714), (16, 0.2141357126916174), (26, 0.20129720491438394), (85, 0.1888156269455851), (182, 0.17519864289671372), (511, 0.14983344511757446), (64, 0.1334698763200967), (203, 0.13043365087797834), (174, 0.1274770097112272), (46, 0.12728508808628056), (101, 0.1258345695455401), (131, 0.12409300211411087), (783, 0.12395663870596615), (138, 0.12201689285407895), (1740, 0.12172743714247967), (169, 0.12099945131897298), (94, 0.1206232815378674), (126, 0.11770343106157138), (788, 0.11687701532975672), (33, 0.11471450976786662), (607, 0.11385173731028674), (1553, 0.11215810964003123), (353, 0.1115232548843458), (661, 0.11065857881944831), (1451, 0.10870982119806225), (720, 0.1033478827643609), (1210, 0.10204412272739494), (618, 0.10012194180553571), (1406, 0.09965851374423224), (954, 0.09887364433194201), (800, 0.09601983271530828), (38, 0.09484585661576721), (307, 0.09340379705375973), (122, 0.

In [ ]:
# print the name of similar movies based on the index

print("Suggested movies for you: \n")

i = 1
for movie in sorted_similarity_movies:
  index=movie[0]
  title_from_index = movies_data[movies_data.index == index]["title"].values[0]
  if i<31:
    print(f"{i}.) {title_from_index}")
    i+=1

Suggested movies for you: 

1.) Iron Man
2.) Iron Man 2
3.) Iron Man 3
4.) Avengers: Age of Ultron
5.) The Avengers
6.) Captain America: Civil War
7.) Captain America: The Winter Soldier
8.) Ant-Man
9.) X-Men
10.) X-Men: Apocalypse
11.) X2
12.) The Incredible Hulk
13.) X-Men: Days of Future Past
14.) X-Men: First Class
15.) G-Force
16.) Mortdecai
17.) The Last Airbender
18.) Kick-Ass 2
19.) Captain America: The First Avenger
20.) Guardians of the Galaxy
21.) Thor: The Dark World
22.) Deadpool
23.) X-Men: The Last Stand
24.) Sky Captain and the World of Tomorrow
25.) Se7en
26.) Tropic Thunder
27.) Zathura: A Space Adventure
28.) Zoom
29.) Contagion
30.) Gothika


In [ ]:
#movies recommendation system
movie_name = input("Enter the name of a movie you like: ")

list_all_titles = movies_data["title"].tolist()

similar_movies = difflib.get_close_matches(movie_name, list_all_titles)

close_match = similar_movies[0]

index_from_title = movies_data[movies_data.title == close_match]["index"].values[0]

similarity_scores = list(enumerate(similarity[index_from_title]))

sorted_similarity_movies = sorted(similarity_scores, key = lambda x:x[1], reverse = True)

print("Movies suggested for you:\n ")

i = 1
for movie in sorted_similarity_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]["title"].values[0]
  if i<=30:
    print(f"{i}.) {title_from_index}")
    i += 1


Enter the name of a movie you like: Batman Begins
Movies suggested for you:
 
1.) Batman Begins
2.) The Dark Knight Rises
3.) The Dark Knight
4.) The Prestige
5.) Batman Returns
6.) Batman
7.) Batman & Robin
8.) Superman
9.) Kick-Ass 2
10.) Kick-Ass
11.) Mad Money
12.) Quest for Camelot
13.) Kung Fu Panda 2
14.) TMNT
15.) Interstellar
16.) GoldenEye
17.) Wonder Boys
18.) Suicide Squad
19.) Watchmen
20.) Taken
21.) Superman II
22.) Superman III
23.) Captain Corelli's Mandolin
24.) Jack and Jill
25.) Insomnia
26.) Abandon
27.) The Girl with the Dragon Tattoo
28.) Charlie's Angels
29.) Inception
30.) Batman Forever
